export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const GET_TAB_INFO = 'GET_TAB_INFO';
export const GET_TAB_INFO_RESPONSE = 'GET_TAB_INFO_RESPONSE';

export const CAPTURE_TAB = 'CAPTURE_TAB';
export const CAPTURE_TAB_RESPONSE = 'CAPTURE_TAB_RESPONSE';

export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_RESPONSE = 'CREATE_CARD_RESPONSE';
