name: Build Chrome Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Create ZIP file
      run: zip -r chrome-extension.zip build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: chrome-extension
        path: chrome-extension.zip